#!/bin/sh /etc/rc.common
START=90
STOP=10
USE_PROCD=1

start_service() {
    config_load vlmcsd
    config_get_bool enabled config enabled 0
    [ "$enabled" -eq 0 ] && return 0
    procd_open_instance
    procd_set_param command /usr/bin/vlmcsd
    procd_append_param command -D
    procd_append_param command -i /etc/vlmcsd.ini
    procd_append_param command -L 0.0.0.0:1688
    procd_append_param command -L ::1688
    procd_append_param command -p /var/run/vlmcsd.pid
    procd_append_param command -l /var/log/vlmcsd.log
    procd_set_param respawn
    procd_set_param file /etc/vlmcsd.ini
    procd_close_instance
}

stop_service() {
    killall vlmcsd 2>/dev/null
    rm -f /var/run/vlmcsd.pid
}

service_triggers() {
    procd_add_reload_trigger vlmcsd
}
